
-- MySQL Script generated by MySQL Workbench
-- Tue Mar 20 14:43:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projet` DEFAULT CHARACTER SET utf8 ;
USE `projet` ;

-- -----------------------------------------------------
-- Table `projet`.`galerie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet`.`galerie` (
  `idgalerie` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idgalerie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet`.`contact` (
  `idcontact` INT NOT NULL AUTO_INCREMENT,
  `contenu` TEXT NULL,
  PRIMARY KEY (`idcontact`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet`.`liens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet`.`liens` (
  `idliens` INT NOT NULL AUTO_INCREMENT,
  `contenu` TEXT NULL,
  PRIMARY KEY (`idliens`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet`.`admin` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet`.`CV`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet`.`CV` (
  `idCV` INT NOT NULL AUTO_INCREMENT,
  `contenu` TEXT NULL,
  PRIMARY KEY (`idCV`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet`.`categ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet`.`categ` (
  `idcateg` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `slug` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcateg`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet`.`categ_has_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet`.`categ_has_admin` (
  `categ_idcateg` INT NOT NULL,
  `admin_idadmin` INT NOT NULL,
  PRIMARY KEY (`categ_idcateg`, `admin_idadmin`),
  INDEX `fk_categ_has_admin_admin1_idx` (`admin_idadmin` ASC),
  INDEX `fk_categ_has_admin_categ_idx` (`categ_idcateg` ASC),
  CONSTRAINT `fk_categ_has_admin_categ`
    FOREIGN KEY (`categ_idcateg`)
    REFERENCES `projet`.`categ` (`idcateg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categ_has_admin_admin1`
    FOREIGN KEY (`admin_idadmin`)
    REFERENCES `projet`.`admin` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet`.`contact_has_categ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet`.`contact_has_categ` (
  `contact_idcontact` INT NOT NULL,
  `categ_idcateg` INT NOT NULL,
  PRIMARY KEY (`contact_idcontact`, `categ_idcateg`),
  INDEX `fk_contact_has_categ_categ1_idx` (`categ_idcateg` ASC),
  INDEX `fk_contact_has_categ_contact1_idx` (`contact_idcontact` ASC),
  CONSTRAINT `fk_contact_has_categ_contact1`
    FOREIGN KEY (`contact_idcontact`)
    REFERENCES `projet`.`contact` (`idcontact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_has_categ_categ1`
    FOREIGN KEY (`categ_idcateg`)
    REFERENCES `projet`.`categ` (`idcateg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet`.`CV_has_categ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet`.`CV_has_categ` (
  `CV_idCV` INT NOT NULL,
  `categ_idcateg` INT NOT NULL,
  PRIMARY KEY (`CV_idCV`, `categ_idcateg`),
  INDEX `fk_CV_has_categ_categ1_idx` (`categ_idcateg` ASC),
  INDEX `fk_CV_has_categ_CV1_idx` (`CV_idCV` ASC),
  CONSTRAINT `fk_CV_has_categ_CV1`
    FOREIGN KEY (`CV_idCV`)
    REFERENCES `projet`.`CV` (`idCV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CV_has_categ_categ1`
    FOREIGN KEY (`categ_idcateg`)
    REFERENCES `projet`.`categ` (`idcateg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet`.`liens_has_categ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet`.`liens_has_categ` (
  `liens_idliens` INT NOT NULL,
  `categ_idcateg` INT NOT NULL,
  PRIMARY KEY (`liens_idliens`, `categ_idcateg`),
  INDEX `fk_liens_has_categ_categ1_idx` (`categ_idcateg` ASC),
  INDEX `fk_liens_has_categ_liens1_idx` (`liens_idliens` ASC),
  CONSTRAINT `fk_liens_has_categ_liens1`
    FOREIGN KEY (`liens_idliens`)
    REFERENCES `projet`.`liens` (`idliens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_liens_has_categ_categ1`
    FOREIGN KEY (`categ_idcateg`)
    REFERENCES `projet`.`categ` (`idcateg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet`.`galerie_has_categ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet`.`galerie_has_categ` (
  `galerie_idgalerie` INT NOT NULL,
  `categ_idcateg` INT NOT NULL,
  PRIMARY KEY (`galerie_idgalerie`, `categ_idcateg`),
  INDEX `fk_galerie_has_categ_categ1_idx` (`categ_idcateg` ASC),
  INDEX `fk_galerie_has_categ_galerie1_idx` (`galerie_idgalerie` ASC),
  CONSTRAINT `fk_galerie_has_categ_galerie1`
    FOREIGN KEY (`galerie_idgalerie`)
    REFERENCES `projet`.`galerie` (`idgalerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_galerie_has_categ_categ1`
    FOREIGN KEY (`categ_idcateg`)
    REFERENCES `projet`.`categ` (`idcateg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
